Repository codestates-seb/seb41_main_035, pull requests merged in 2023-02, with the labels that each got.

#119 ✨ feat: about css 수정”
  client/src/pages/About.js
  client/src/svg/About.png
Labels: frontend, 박영선

#121 ✨ feat: 로그인, 사이드바 css 수정”
  client/src/components/LoginModal/LoginModal.js
  client/src/components/Sidebar.js
  client/src/components/Signup/Signup.js
  client/src/pages/PostUpload.js
Labels: frontend, 박영선

#123 ✨ feat:all 수정
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.js
  client/src/components/ChatWindow.js
  client/src/components/ChattingList.js
  client/src/components/Footer.js
  client/src/components/ImageInput.js
  client/src/components/Item.js
  client/src/components/LoginHeader.js
  client/src/components/SearchBox.js
  client/src/components/Sidebar.js
  client/src/components/UserInfo.js
  client/src/pages/Chat.js
  client/src/pages/EditItembar.js
  client/src/pages/EditPost.js
  client/src/pages/PostUploadBar.js
  client/src/pages/Profile.js
Labels: 김나율, frontend

#127 refactor: Github Action 스크립트 수정
  .github/workflows/gradle-publish.yml
  .github/workflows/gradle-pull-request.yml
  server/Dockerfile
  server/src/main/resources/application-prod.yml
  server/src/main/resources/static/index.html
Labels: 이도형, backend

#128 refactor: Github Action 스크립트 수정
  .github/workflows/gradle-publish.yml
  .github/workflows/gradle-pull-request.yml
  server/Dockerfile
  server/src/main/resources/application-prod.yml
  server/src/main/resources/static/index.html
Labels: 이도형, backend
