Repository codestates-seb/seb41_main_035, pull requests merged in 2023-01, with the labels that each got.

#5 Feat/fe/ header
  client/package-lock.json
  client/package.json
  client/src/components/LoginHeader.js
  client/src/components/LogoutHeader.js
Labels: 김나율

#12 Feat/fe/home
  client/src/App.js
  client/src/components/LoginHeader.js
  client/src/components/LogoutHeader.js
  client/src/components/PostBox.js
  client/src/db/dummyData.json
  client/src/pages/Home.js
Labels: 김나율, frontend

#8 feat: 로그인/로그아웃 기능 구현
  server/build.gradle
  server/src/main/java/com/lookatme/server/ControllerAdvice.java
  server/src/main/java/com/lookatme/server/auth/dto/LoginDto.java
  server/src/main/java/com/lookatme/server/auth/dto/MemberPrincipal.java
  server/src/main/java/com/lookatme/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/lookatme/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/lookatme/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/lookatme/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/lookatme/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/lookatme/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/lookatme/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/lookatme/server/auth/jwt/RedisRepository.java
  server/src/main/java/com/lookatme/server/auth/service/AuthService.java
  server/src/main/java/com/lookatme/server/auth/userdetails/MemberDetails.java
  server/src/main/java/com/lookatme/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/lookatme/server/auth/utils/ErrorResponder.java
  server/src/main/java/com/lookatme/server/auth/utils/MemberAuthorityUtils.java
  server/src/main/java/com/lookatme/server/common/dto/ErrorResponseDto.java
  server/src/main/java/com/lookatme/server/config/RedisConfiguration.java
  server/src/main/java/com/lookatme/server/config/SecurityConfiguration.java
  server/src/main/java/com/lookatme/server/exception/ErrorCode.java
  server/src/main/java/com/lookatme/server/exception/ErrorLogicException.java
  server/src/main/java/com/lookatme/server/exception/comment/CommentNotFoundException.java
  server/src/main/java/com/lookatme/server/member/controller/MemberController.java
  server/src/main/java/com/lookatme/server/member/dto/MemberDto.java
  server/src/main/java/com/lookatme/server/member/entity/Member.java
  server/src/main/java/com/lookatme/server/member/mapper/MemberMapper.java
  server/src/main/java/com/lookatme/server/member/repository/MemberRepository.java
  server/src/main/java/com/lookatme/server/member/service/MemberService.java
  server/src/main/java/com/lookatme/server/validator/Password.java
  server/src/main/java/com/lookatme/server/validator/PasswordValidator.java
  server/src/main/resources/application.yml
Labels: 이도형, backend

#18 feat: 소셜 로그인 기능 구현
  server/src/main/java/com/lookatme/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/lookatme/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/lookatme/server/auth/handler/OauthAuthenticationSuccessHandler.java
  server/src/main/java/com/lookatme/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/lookatme/server/auth/jwt/RedisRepository.java
  server/src/main/java/com/lookatme/server/auth/service/AuthService.java
  server/src/main/java/com/lookatme/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/lookatme/server/config/SecurityConfiguration.java
  server/src/main/java/com/lookatme/server/exception/ErrorCode.java
  server/src/main/java/com/lookatme/server/member/controller/MemberController.java
  server/src/main/java/com/lookatme/server/member/dto/MemberDto.java
  server/src/main/java/com/lookatme/server/member/entity/Member.java
  server/src/main/java/com/lookatme/server/member/repository/MemberRepository.java
  server/src/main/java/com/lookatme/server/member/service/MemberService.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/index.html
  server/src/test/java/com/lookatme/server/ServerApplicationTests.java
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
Labels: 이도형, backend

#20 build: 백엔드 애플리케이션 무중단 배포
  .github/workflows/gradle-publish.yml
  server/appspec.yml
  server/build.gradle
  server/scripts/health.sh
  server/scripts/profile.sh
  server/scripts/start.sh
  server/scripts/stop.sh
  server/scripts/switch.sh
  server/src/main/java/com/lookatme/server/auth/controller/AuthController.java
  server/src/main/java/com/lookatme/server/config/SecurityConfiguration.java
  server/src/main/java/com/lookatme/server/member/controller/MemberController.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/index.html
  server/src/test/java/com/lookatme/server/comment/CommentControllerTest.java
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
Labels: 이도형, backend

#22 Feat/fe/login
  client/src/App.js
  client/src/components/LoginHeader.js
Labels: frontend, 이승준

#21 Feat/fe/autocomplete
  client/package-lock.json
  client/package.json
  client/src/components/LoginHeader.js
  client/src/components/LogoutHeader.js
  client/src/components/SearchBox.js
  client/src/pages/Home.js
Labels: 김나율, frontend

#25 Feat/fe/categorypage
  client/src/App.js
  client/src/components/LoginHeader.js
  client/src/components/SearchBox.js
  client/src/components/Sidebar.js
  client/src/pages/Bottom.js
  client/src/pages/Hat.js
  client/src/pages/Onepiece.js
  client/src/pages/Outer.js
  client/src/pages/Shoes.js
  client/src/pages/Top.js
Labels: 김나율, frontend

#29 Feat/be/comment
  server/src/main/java/com/lookatme/server/comment/controller/CommentController.java
  server/src/main/java/com/lookatme/server/comment/dto/CommentResponseDto.java
  server/src/main/java/com/lookatme/server/comment/entity/Comment.java
  server/src/main/java/com/lookatme/server/comment/service/CommentService.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/lookatme/server/comment/CommentControllerTest.java
Labels: 조혜주, backend

#34 Feat/be/message
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/lookatme/server/exception/ErrorCode.java
  server/src/main/java/com/lookatme/server/exception/message/MessageNotFoundException.java
  server/src/main/java/com/lookatme/server/exception/message/MessageNotSendToSelfException.java
  server/src/main/java/com/lookatme/server/message/controller/MessageController.java
  server/src/main/java/com/lookatme/server/message/dto/MessagePostDto.java
  server/src/main/java/com/lookatme/server/message/dto/MessageResponseDto.java
  server/src/main/java/com/lookatme/server/message/entity/Message.java
  server/src/main/java/com/lookatme/server/message/repository/MessageRepository.java
  server/src/main/java/com/lookatme/server/message/service/MessageService.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/lookatme/server/message/MessageControllerTest.java
Labels: 조혜주, backend

#35 Feat/fe/chatting
  client/package-lock.json
  client/src/App.css
  client/src/components/Avatar.js
  client/src/components/ChatWindow.js
  client/src/components/ChattingList.js
  client/src/components/Footer.js
  client/src/components/LoginHeader.js
  client/src/components/LoginModal/LoginModal.js
  client/src/components/PostBox.js
  client/src/components/SearchBox.js
  client/src/components/Sidebar.js
  client/src/components/UserInfo.js
  client/src/db/dummyData.json
  client/src/pages/Bottom.js
  client/src/pages/Hat.js
  client/src/pages/Home.js
  client/src/pages/Onepiece.js
  client/src/pages/Outer.js
  client/src/pages/Shoes.js
  client/src/pages/Top.js
Labels: 김나율, frontend

#39 ✨ feat: dropdown 디자인 수정
  client/src/components/Dropdown.js
Labels: 박영선

#40 ♻️ refactor: 리팩토링 및 디자인 수정”
  client/package-lock.json
  client/src/components/Footer.js
Labels: 박영선

#43 ✨ feat: sidebar 디자인 수정
  client/src/components/Sidebar.js
Labels: 박영선

#44 Feat/fe/postdetail
  client/src/App.js
  client/src/components/Comment.js
  client/src/components/Item.js
  client/src/components/LoginHeader.js
  client/src/components/PostBox.js
  client/src/db/dummyData.json
  client/src/pages/PostView.js
  client/src/svg/Rent.svg
Labels: 김나율, frontend

#45 fix: cors 설정 수정
  server/src/main/java/com/lookatme/server/config/SecurityConfiguration.java
  server/src/main/resources/static/index.html
Labels: 이도형, backend

#50 build: pull request 할 때 자동 빌드 테스트 진행 기능 추가
  .github/workflows/gradle-publish.yml
  .github/workflows/gradle-pull-request.yml
  server/src/main/java/com/lookatme/server/config/SecurityConfiguration.java
Labels: 이도형, backend

#51 Feat/be/message 추가 기능 구현
  server/src/main/java/com/lookatme/server/message/controller/MessageController.java
  server/src/main/java/com/lookatme/server/message/repository/MessageRepository.java
  server/src/main/java/com/lookatme/server/message/service/MessageService.java
  server/src/test/java/com/lookatme/server/message/MessageControllerTest.java
Labels: 조혜주, backend

#52 Feat/fe/add comment
  client/src/App.js
  client/src/components/Comment.js
  client/src/components/Item.js
  client/src/components/LoginHeader.js
  client/src/components/LogoutHeader.js
  client/src/components/PostBox.js
  client/src/db/dummyData.json
  client/src/pages/Bottom.js
  client/src/pages/Hat.js
  client/src/pages/Home.js
  client/src/pages/Onepiece.js
  client/src/pages/Outer.js
  client/src/pages/PostView.js
  client/src/pages/Shoes.js
  client/src/pages/Top.js
Labels: 김나율, frontend

#48 Feat/be/member
  server/.gitignore
  server/src/docs/asciidoc/index.adoc
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/java/com/lookatme/server/ControllerAdvice.java
  server/src/main/java/com/lookatme/server/auth/controller/AuthController.java
  server/src/main/java/com/lookatme/server/auth/dto/MemberPrincipal.java
  server/src/main/java/com/lookatme/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/lookatme/server/auth/handler/LoginTransactionalListener.java
  server/src/main/java/com/lookatme/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/lookatme/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/lookatme/server/auth/handler/OauthAuthenticationSuccessHandler.java
  server/src/main/java/com/lookatme/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/lookatme/server/auth/service/AuthService.java
  server/src/main/java/com/lookatme/server/auth/userdetails/MemberDetails.java
  server/src/main/java/com/lookatme/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/lookatme/server/auth/utils/ErrorResponder.java
  server/src/main/java/com/lookatme/server/common/dto/ErrorResponseDto.java
  server/src/main/java/com/lookatme/server/config/SecurityConfiguration.java
  server/src/main/java/com/lookatme/server/exception/ErrorCode.java
  server/src/main/java/com/lookatme/server/member/controller/MemberController.java
  server/src/main/java/com/lookatme/server/member/dto/MemberDto.java
  server/src/main/java/com/lookatme/server/member/entity/Account.java
  server/src/main/java/com/lookatme/server/member/entity/Follow.java
  server/src/main/java/com/lookatme/server/member/entity/Member.java
  server/src/main/java/com/lookatme/server/member/entity/MemberStatus.java
  server/src/main/java/com/lookatme/server/member/entity/OauthPlatform.java
  server/src/main/java/com/lookatme/server/member/repository/MemberRepository.java
  server/src/main/java/com/lookatme/server/member/service/MemberService.java
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
  server/src/test/java/com/lookatme/server/auth/controller/AuthControllerTest.java
  server/src/test/java/com/lookatme/server/auth/jwt/JwtTokenizerTest.java
  server/src/test/java/com/lookatme/server/comment/CommentControllerTest.java
  server/src/test/java/com/lookatme/server/config/CustomTestConfiguration.java
  server/src/test/java/com/lookatme/server/config/WithAuthMember.java
  server/src/test/java/com/lookatme/server/config/WithAuthMemberSecurityContextFactory.java
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
  server/src/test/java/com/lookatme/server/member/service/MemberServiceTest.java
  server/src/test/java/com/lookatme/server/message/MessageControllerTest.java
Labels: 이도형, backend

#53 ✨ feat: 추가버튼 누를시 업로드바 추가”
  client/src/App.js
  client/src/components/Dropdown.js
  client/src/components/ImageInput.js
  client/src/components/ItemImageInput.js
  client/src/components/Plusbutton.js
  client/src/pages/PostUpload.js
  client/src/pages/PostUploadBar.js
  client/src/store/userStore.js
Labels: 박영선

#59 Feat/fe/add post
  client/src/components/Comment.js
  client/src/components/LoginHeader.js
  client/src/components/PostBox.js
  client/src/components/SearchBox.js
  client/src/components/Sidebar.js
  client/src/pages/Bottom.js
  client/src/pages/Hat.js
  client/src/pages/Home.js
  client/src/pages/Onepiece.js
  client/src/pages/Outer.js
  client/src/pages/PostView.js
  client/src/pages/Shoes.js
  client/src/pages/Top.js
Labels: 김나율, frontend

#55 Feat/be/message
  server/src/main/java/com/lookatme/server/message/controller/MessageController.java
  server/src/main/java/com/lookatme/server/message/service/MessageService.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/lookatme/server/message/MessageControllerTest.java
Labels: 조혜주, backend

#56 feat: Embedded Redis 추가
  .github/workflows/gradle-pull-request.yml
  server/build.gradle
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/java/com/lookatme/server/auth/controller/AuthController.java
  server/src/main/java/com/lookatme/server/auth/handler/LoginTransactionalListener.java
  server/src/main/java/com/lookatme/server/auth/jwt/RedisRepository.java
  server/src/main/java/com/lookatme/server/auth/service/AuthService.java
  server/src/main/java/com/lookatme/server/config/EmbeddedRedisConfig.java
  server/src/test/java/com/lookatme/server/auth/controller/AuthControllerSliceTest.java
  server/src/test/java/com/lookatme/server/auth/controller/AuthControllerTest.java
  server/src/test/java/com/lookatme/server/member/service/MemberServiceTest.java
Labels: 이도형, backend

#60 feat: 회원 프로필 사진 등록 기능 추가
  server/build.gradle
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/java/com/lookatme/server/ControllerAdvice.java
  server/src/main/java/com/lookatme/server/exception/ErrorCode.java
  server/src/main/java/com/lookatme/server/file/service/FileController.java
  server/src/main/java/com/lookatme/server/file/service/FileService.java
  server/src/main/java/com/lookatme/server/member/controller/MemberController.java
  server/src/main/java/com/lookatme/server/member/dto/MemberDto.java
  server/src/main/java/com/lookatme/server/member/entity/Member.java
  server/src/main/java/com/lookatme/server/member/mapper/MemberMapper.java
  server/src/main/java/com/lookatme/server/member/service/MemberService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
  server/src/test/java/com/lookatme/server/member/service/MemberServiceTest.java
Labels: 이도형, backend

#65 Feat/fe/itemuploadbar
  client/src/App.js
  client/src/components/ImageInput.js
  client/src/components/ItemImageInput.js
  client/src/components/Plusbutton.js
  client/src/pages/PostUpload.js
  client/src/pages/PostUploadBar.js
Labels: frontend, 박영선

#63 Feat/fe/all fix
  client/src/App.js
  client/src/components/Avatar.js
  client/src/components/Comment.js
  client/src/components/LoginHeader.js
  client/src/components/PostBox.js
  client/src/components/SearchBox.js
  client/src/components/Sidebar.js
  client/src/constants/index.js
  client/src/db/CategoryData.json
  client/src/pages/Bottom.js
  client/src/pages/Category.js
  client/src/pages/Hat.js
  client/src/pages/Home.js
  client/src/pages/Onepiece.js
  client/src/pages/Outer.js
  client/src/pages/PostView.js
  client/src/pages/Top.js
  client/src/utils/CommentApi.js
Labels: 김나율, frontend

#66 ✨ feat: 게시글업로드 수정
  client/package-lock.json
  client/src/components/ImageInput.js
  client/src/components/ItemImageInput.js
  client/src/components/Plusbutton.js
  client/src/pages/PostUpload.js
  client/src/pages/PostUploadBar.js
Labels: frontend, 박영선

#72 Feat/fe/post function
  client/src/App.css
  client/src/App.js
  client/src/components/ChatWindow.js
  client/src/components/ChattingList.js
  client/src/components/Comment.js
  client/src/components/Dropdown.js
  client/src/components/ImageInput.js
  client/src/components/Item.js
  client/src/components/ItemImageInput.js
  client/src/components/LoginHeader.js
  client/src/components/PostBox.js
  client/src/components/Sidebar.js
  client/src/components/Slider.js
  client/src/components/UserInfo.js
  client/src/constants/index.js
  client/src/pages/Category.js
  client/src/pages/Home.js
  client/src/pages/PostUpload.js
  client/src/pages/PostUploadBar.js
  client/src/pages/PostView.js
  client/src/pages/Profile.js
  client/src/svg/2109.i121.033.S.m005.c13.isometric fashion clothes infographics.jpg
  client/src/svg/Site.webp
Labels: 김나율, frontend

#74 🐛 fix:error fix
  client/src/components/UserInfo.js
  client/src/pages/PostView.js
Labels: 김나율, frontend

#70 Feat/be/comment
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/lookatme/server/board/dto/BoardResponseDto.java
  server/src/main/java/com/lookatme/server/board/entity/Board.java
  server/src/main/java/com/lookatme/server/comment/controller/CommentController.java
  server/src/main/java/com/lookatme/server/comment/dto/CommentPostDto.java
  server/src/main/java/com/lookatme/server/comment/dto/CommentResponseDto.java
  server/src/main/java/com/lookatme/server/comment/entity/Comment.java
  server/src/main/java/com/lookatme/server/comment/repository/CommentRepository.java
  server/src/main/java/com/lookatme/server/comment/service/CommentService.java
  server/src/main/java/com/lookatme/server/exception/ErrorCode.java
  server/src/main/java/com/lookatme/server/exception/board/BoardNotFoundException.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/lookatme/server/comment/CommentControllerTest.java
Labels: 조혜주, backend

#75 Feat/be/message
  server/src/main/java/com/lookatme/server/message/controller/MessageController.java
  server/src/main/java/com/lookatme/server/message/dto/MessageResponseDto.java
  server/src/main/java/com/lookatme/server/message/entity/Message.java
  server/src/main/java/com/lookatme/server/message/repository/MessageRepository.java
  server/src/main/java/com/lookatme/server/message/service/MessageService.java
  server/src/main/resources/data.sql
  server/src/test/java/com/lookatme/server/message/MessageControllerTest.java
Labels: 조혜주, backend

#77 💄 style: 게시글, 사이드바 스타일변경”
  client/package-lock.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/components/ImageInput.js
  client/src/components/ItemImageInput.js
  client/src/components/LoginHeader.js
  client/src/components/Plusbutton.js
  client/src/components/Sidebar.js
  client/src/pages/PostUpload.js
  client/src/pages/PostUploadBar.js
Labels: frontend, 박영선

#82 refactor: FollowService 분리
  server/src/main/generated/com/lookatme/server/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/lookatme/server/product/mapper/ProductMapperImpl.java
  server/src/main/generated/com/lookatme/server/rental/mapper/RentalMapperImpl.java
  server/src/main/java/com/lookatme/server/auth/handler/OauthAuthenticationSuccessHandler.java
  server/src/main/java/com/lookatme/server/board/dto/BoardResponseListDto.java
  server/src/main/java/com/lookatme/server/board/service/BoardService.java
  server/src/main/java/com/lookatme/server/member/controller/MemberController.java
  server/src/main/java/com/lookatme/server/member/entity/Member.java
  server/src/main/java/com/lookatme/server/member/repository/FollowRepository.java
  server/src/main/java/com/lookatme/server/member/service/FollowService.java
  server/src/main/java/com/lookatme/server/member/service/MemberService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
  server/src/test/java/com/lookatme/server/member/service/FollowServiceTest.java
  server/src/test/java/com/lookatme/server/member/service/MemberServiceTest.java
Labels: 이도형, backend

#84 feat: 팔로우 기능 개선
  server/src/main/generated/com/lookatme/server/board/mapper/BoardMapperImpl.java
  server/src/main/java/com/lookatme/server/board/controller/BoardController.java
  server/src/main/java/com/lookatme/server/board/service/BoardService.java
  server/src/main/java/com/lookatme/server/member/entity/Member.java
  server/src/main/java/com/lookatme/server/member/repository/FollowRepository.java
  server/src/main/java/com/lookatme/server/member/service/FollowService.java
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
  server/src/test/java/com/lookatme/server/member/service/FollowServiceTest.java
Labels: 이도형, backend

#86 ✨ feat: 서비스소개, 채팅 수정”
  client/package-lock.json
  client/src/App.js
  client/src/components/ChatWindow.js
  client/src/components/ChattingList.js
  client/src/components/LoginHeader.js
  client/src/components/Slider.js
  client/src/pages/About.js
  client/src/pages/PostView.js
  client/src/svg/Logo.svg
Labels: frontend, 박영선

#90 feat: 게시글 등록 / 수정 기능 구현
  server/src/main/generated/com/lookatme/server/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/lookatme/server/product/mapper/ProductMapperImpl.java
  server/src/main/generated/com/lookatme/server/rental/mapper/RentalMapperImpl.java
  server/src/main/java/com/lookatme/server/board/controller/BoardController.java
  server/src/main/java/com/lookatme/server/board/dto/SimpleBoardResponseDto.java
  server/src/main/java/com/lookatme/server/board/entity/Board.java
  server/src/main/java/com/lookatme/server/board/entity/BoardProduct.java
  server/src/main/java/com/lookatme/server/board/repository/BoardRepository.java
  server/src/main/java/com/lookatme/server/board/service/BoardService.java
  server/src/main/java/com/lookatme/server/file/FileService.java
  server/src/main/java/com/lookatme/server/message/repository/MessageRepository.java
  server/src/main/java/com/lookatme/server/product/controller/ProductController.java
  server/src/main/java/com/lookatme/server/product/dto/ProductPatchDto.java
  server/src/main/java/com/lookatme/server/product/dto/V2/ProductPatchDtoV2.java
  server/src/main/java/com/lookatme/server/product/dto/V2/ProductPostDtoV2.java
  server/src/main/java/com/lookatme/server/product/dto/V2/ProductResponseDtoV2.java
  server/src/main/java/com/lookatme/server/product/entity/Product.java
  server/src/main/java/com/lookatme/server/product/mapper/ProductMapper.java
  server/src/main/java/com/lookatme/server/product/repository/ProductRepository.java
  server/src/main/java/com/lookatme/server/product/service/ProductService.java
  server/src/main/java/com/lookatme/server/rental/dto/RentalPatchDto.java
  server/src/main/java/com/lookatme/server/rental/dto/RentalResponseDto.java
  server/src/main/java/com/lookatme/server/rental/entity/Rental.java
  server/src/main/java/com/lookatme/server/rental/repository/RentalRepository.java
  server/src/main/java/com/lookatme/server/rental/service/RentalService.java
Labels: 이도형, backend

#91 refactor: 회원 탈퇴 기능 개선
  server/src/main/generated/com/lookatme/server/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/lookatme/server/product/mapper/ProductMapperImpl.java
  server/src/main/generated/com/lookatme/server/rental/mapper/RentalMapperImpl.java
  server/src/main/java/com/lookatme/server/member/dto/MemberDto.java
  server/src/main/java/com/lookatme/server/member/entity/Member.java
  server/src/main/java/com/lookatme/server/member/entity/MemberStatus.java
  server/src/main/java/com/lookatme/server/member/repository/FollowRepository.java
  server/src/main/java/com/lookatme/server/member/service/FollowService.java
  server/src/main/java/com/lookatme/server/member/service/MemberService.java
  server/src/main/java/com/lookatme/server/rental/repository/RentalRepository.java
  server/src/main/java/com/lookatme/server/rental/service/RentalService.java
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
  server/src/test/java/com/lookatme/server/member/service/MemberServiceTest.java
Labels: 이도형, backend

#92 Feat/be/message
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/lookatme/server/message/controller/MessageController.java
  server/src/main/java/com/lookatme/server/message/dto/MessageResponseDto.java
  server/src/main/java/com/lookatme/server/message/entity/Message.java
  server/src/main/java/com/lookatme/server/message/repository/MessageRepository.java
  server/src/main/java/com/lookatme/server/message/service/MessageService.java
  server/src/main/resources/data.sql
  server/src/test/java/com/lookatme/server/message/MessageControllerTest.java
Labels: 조혜주, backend

#95 feat: 게시글 좋아요 기능 구현
  server/src/main/java/com/lookatme/server/board/controller/BoardController.java
  server/src/main/java/com/lookatme/server/board/service/BoardService.java
  server/src/main/java/com/lookatme/server/likes/entity/Likes.java
  server/src/main/java/com/lookatme/server/likes/repository/LikesRepository.java
  server/src/main/java/com/lookatme/server/likes/service/LikesService.java
Labels: 조혜주, backend

#98 ✨ feat: 댓글 수정기능, 좋아요, css수정”
  client/src/components/Comment.js
  client/src/components/ImageInput.js
  client/src/components/Item.js
  client/src/components/ItemImageInput.js
  client/src/components/PostBox.js
  client/src/components/Sidebar.js
  client/src/pages/Category.js
  client/src/pages/PostUpload.js
  client/src/pages/PostUploadBar.js
  client/src/pages/PostView.js
Labels: frontend, 박영선

#97 Feat/fe/function
  client/src/App.js
  client/src/components/ChatWindow.js
  client/src/components/ChattingList.js
  client/src/components/Comment.js
  client/src/components/Item.js
  client/src/components/LoginHeader.js
  client/src/components/PostBox.js
  client/src/components/Slider.js
  client/src/pages/Category.js
  client/src/pages/Chat.js
  client/src/pages/EditPost.js
  client/src/pages/Home.js
  client/src/pages/PostUpload.js
  client/src/pages/PostView.js
  client/src/pages/Profile.js
  client/src/svg/SiteInfo.webp
Labels: 김나율, frontend

#99 refactor: 팔로우 목록 조회 방법 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/generated/com/lookatme/server/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/lookatme/server/product/mapper/ProductMapperImpl.java
  server/src/main/generated/com/lookatme/server/rental/mapper/RentalMapperImpl.java
  server/src/main/java/com/lookatme/server/member/controller/MemberController.java
  server/src/main/java/com/lookatme/server/member/repository/FollowRepository.java
  server/src/main/java/com/lookatme/server/member/service/FollowService.java
  server/src/test/java/com/lookatme/server/member/controller/MemberControllerTest.java
  server/src/test/java/com/lookatme/server/member/service/FollowServiceTest.java
Labels: 이도형, backend

#100 refactor: 게시글 CRUD 관련 RestDocs 작성
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/lookatme/server/ControllerAdvice.java
  server/src/main/java/com/lookatme/server/board/controller/BoardController.java
  server/src/main/java/com/lookatme/server/board/dto/BoardPatchDto.java
  server/src/main/java/com/lookatme/server/board/dto/BoardPostDto.java
  server/src/main/java/com/lookatme/server/board/dto/BoardResponseDto.java
  server/src/main/java/com/lookatme/server/board/entity/Board.java
  server/src/main/java/com/lookatme/server/board/entity/BoardProduct.java
  server/src/main/java/com/lookatme/server/board/service/BoardService.java
  server/src/main/java/com/lookatme/server/comment/dto/CommentResponseDtoV2.java
  server/src/main/java/com/lookatme/server/member/mapper/MemberMapper.java
  server/src/main/java/com/lookatme/server/product/dto/BoardProductsResponseDto.java
  server/src/main/java/com/lookatme/server/product/dto/ProductPatchDto.java
  server/src/main/java/com/lookatme/server/product/dto/ProductPostDto.java
  server/src/main/java/com/lookatme/server/product/entity/Product.java
  server/src/main/java/com/lookatme/server/product/service/ProductService.java
  server/src/main/java/com/lookatme/server/rental/dto/RentalResponseDto.java
  server/src/main/java/com/lookatme/server/rental/entity/Rental.java
  server/src/test/java/com/lookatme/server/board/controller/BoardControllerTest.java
  server/src/test/java/com/lookatme/server/util/ApiDocumentUtils.java
Labels: 이도형, backend

#102 feat: 게시글 조회 시 좋아요 유무 필드 추가
  server/src/main/generated/com/lookatme/server/board/mapper/BoardMapperImpl.java
  server/src/main/generated/com/lookatme/server/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/lookatme/server/product/mapper/ProductMapperImpl.java
  server/src/main/generated/com/lookatme/server/rental/mapper/RentalMapperImpl.java
  server/src/main/java/com/lookatme/server/board/dto/BoardResponseDto.java
  server/src/main/java/com/lookatme/server/board/entity/Board.java
  server/src/main/java/com/lookatme/server/board/repository/BoardRepository.java
  server/src/main/java/com/lookatme/server/board/service/BoardService.java
  server/src/main/java/com/lookatme/server/comment/service/CommentService.java
  server/src/main/java/com/lookatme/server/likes/repository/LikesRepository.java
  server/src/main/java/com/lookatme/server/likes/service/LikesService.java
  server/src/test/java/com/lookatme/server/board/controller/BoardControllerTest.java
Labels: 이도형, backend

#103 Feat/fe/function
  client/src/components/HamBar.js
  client/src/components/LoginHeader.js
  client/src/components/Sidebar.js
  client/src/components/UserInfo.js
  client/src/pages/Category.js
  client/src/pages/Chat.js
  client/src/pages/EditItembar.js
  client/src/pages/EditPost.js
  client/src/pages/Home.js
  client/src/pages/Profile.js
Labels: 김나율, frontend

#107 feat: 게시글 좋아요 test 코드 및 rest docs 작성
  server/src/docs/asciidoc/index.adoc
  server/src/test/java/com/lookatme/server/board/controller/BoardControllerTest.java
Labels: 조혜주, backend

#108 refactor: boardId 타입 수정
  server/src/main/java/com/lookatme/server/comment/controller/CommentController.java
  server/src/main/java/com/lookatme/server/comment/repository/CommentRepository.java
  server/src/main/java/com/lookatme/server/comment/service/CommentService.java
  server/src/test/java/com/lookatme/server/comment/CommentControllerTest.java
Labels: 조혜주, backend

#113 ✨ feat: 댓글 및 좋아요 기능, css 수정”
  .DS_Store
  client/src/App.css
  client/src/components/Comment.js
  client/src/components/LoginModal/LoginModal.js
  client/src/components/Post.js
  client/src/components/PostBox.js
  client/src/components/Sidebar.js
  client/src/components/Slider.js
  client/src/components/UserInfo.js
  client/src/pages/About.js
  client/src/pages/Category.js
  client/src/pages/Home.js
  client/src/pages/PostView.js
  client/src/pages/Profile.js
  client/src/store/userStore.js
  client/src/svg/2109.i121.033.S.m005.c13.isometric fashion clothes infographics.jpg
  client/src/svg/Site.webp
  client/src/svg/SiteInfo.webp
Labels: frontend, 박영선

#117 💄 style: 전체적 Css 수정”
  client/src/components/LoginHeader.js
  client/src/components/UserInfo.js
  client/src/pages/About.js
  client/src/pages/Chat.js
Labels: frontend, 박영선
